### ISSUE TITLE
The following libraries were not found

### ISSUE THREAD

**Issue by jerrybarnett** [harbra/IRBridge#2]
I did a clone of your IRBridge, and went to KiCad to open the irbridge.pro project.  I received the following error:
The following libraries were not found:
          - kicad-ESP8266\ESP8266
          - \home\harald\Basteln\KiCadLibrary\mylibrary

Can this library be provided or can you provide where it can be found?

**Comment by harbra** [comment]
The ESP8266 library can be found on [github](https://github.com/jdunmire/kicad-ESP8266).
The other library is where I keep my custom footprints. I added it for reference to the /pcb/ subfolder.
